kind: MLApp
metadata:
  name: r-studio
spec:
  tasks:
  - name: run
    resources:
    - name: script
      replicas: 1
      restartPolicy: Never
      maxRestartCount: 0
      allowFail: true
      images:
        cpu: "r-base:3.4.2"
      command: Rscript hello.R
      workdir: "$SRC_DIR"
      default_volume_mapping: true
  uix:
  - name: rstudio
    displayName: RStudio
    images:
      cpu: "rocker/rstudio:3.3.1"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 4000m
        memory: 8Gi
    ports:
    - port: 80
      targetPort: 8787
      protocol: TCP
      name: http
    default_volume_mapping: true
    default_mount_path: "/home/rstudio"
  volumes:
  - isLibDir: false
    mountPath: /workspace/training
    name: training
    clusterStorage: {{ .storage.value }}
    subPath: training
  - gitRepo:
      repository: {{.src.value}}
    isLibDir: false
    mountPath: /workspace/src
    name: src
  - isLibDir: true
    mountPath: /workspace/packages
    name: packages
    clusterStorage: {{ .storage.value }}
    subPath: packages
  - isLibDir: false
    mountPath: /workspace/data
    name: data
    clusterStorage: {{ .storage.value }}
    subPath: data
  - isLibDir: false
    mountPath: /workspace/code
    name: code
    clusterStorage: {{ .storage.value }}
    subPath: code
